# Generated by Django 5.1.6 on 2025-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
